name    'alkivi-motd'
version '0.0.5'
source 'https://github.com/alkivi-sas/puppet-motd'
author 'alkivi'
license 'LGPLv3'
summary 'Controls motd file on unix system'
description 'Setup motd and give ability to register module'
project_page 'https://github.com/alkivi-sas/puppet-motd'
dependency 'puppetlabs/concat', '>=1.0.0'
